### ISSUE TITLE
Workbook queries fail: SecretsManager encryption not initialized

### ISSUE THREAD

**Issue by bradleybossard** [kineticadb/examples#1]
I've been attempting to work through the quick start tutorials here

https://docs.kinetica.com/7.1/guides/quickstart-guide/

After installing Kinectica on Linux via the one-liner, then navigating to the GAdmin menu and running either of the following two queries

```
CREATE OR REPLACE DATA SOURCE quickstart
LOCATION = 'S3'
WITH OPTIONS (
    ANONYMOUS = 'true',
    BUCKET NAME = 'quickstartpublic',
    REGION = 'us-east-1'
)
```

```
CREATE or REPLACE DATA SOURCE taxi_streaming_ds
LOCATION = 'KAFKA://quickstart.kinetica.com:9092'
WITH OPTIONS (KAFKA_TOPIC_NAME = 'nyctaxi')
```

I get the following errors

```
EXECUTING...


SQL: CREATE or REPLACE DATA SOURCE taxi_streaming_ds
LOCATION = 'KAFKA://quickstart.kinetica.com:9092'
WITH OPTIONS (KAFKA_TOPIC_NAME = 'nyctaxi')
==================================================================================================================================================
Time zone set to Greenwich Mean Time, system default is Coordinated Universal Time
Connection successful
Catalog [Kinetica]
Deployment Time: 0.717 s
[GPUdb]executeSql: Error: 'SecretsManager encryption not initialized (S/SMc:347) (S/SDc:1495); error in Job process'
System Results Limit: 10000

EXECUTION ERROR OCCURRED
```

Is there a step I am missing about configuring AWS on my side, or is this a misconfiguration on the sample data side?

**Comment by MattSkewbie** [comment]
Hi Bradley,

We've seen this error message before. There's some issue in the ``kinetica`` script that causes the ``/opt/gpudb/.secrets`` file to not be made during installation. Though the issue seems to appear only intermittently. One of our engineers is currently looking into it, so hopefully we get this remedied in the near future.

In the mean time, one way to get around the issue is to simply reinstall. It's a drag, but that seems to have solved the issue for other users in the past. Let me know if this does not fix the issue.

With regard to the SQL you posted, I ran through it this morning on an Azure Marketplace instance and it worked like a charm. So I think the issue is isolated to the installation in this case.
